<?php

class StoreProductsModel extends DatabaseService {

    private $modelProductsArray = [];
    private $sqlProducts;
    private $productModelDatabase;

    public function fetchProductsData()
    {
        $this->productModelDatabase = new DatabaseService();
        $this->productModelDatabase->connect();

        $typeId = filter_input(INPUT_GET, "typeId", FILTER_SANITIZE_STRING);
        $this->sqlProducts = "SELECT t.name AS productTypeName, p.name AS productName FROM product_types t JOIN products p ON t.id = p.id_product_types WHERE t.id = $typeId";

        foreach ($this->productModelDatabase->connect()->query($this->sqlProducts)->fetchAll(PDO::FETCH_ASSOC) as $item){
            array_push($this->modelProductsArray, $item);
        }

        ///
        print_r("{");
        print_r("\n\n\"productType\": \"" . $this->modelProductsArray[0]['productTypeName']. "\",");
        print_r("\n\"products\": [\n");
        echo "\n";
        foreach ($this->modelProductsArray as $item){
            echo "{\n\"name\" : ";
            print_r("\"" . $item['productName'] . "\"");
            echo "\n}, ";
        }
        print_r("\n],\n");
        print_r("url\": " .$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI']);
        print_r("\n\n}");
    ///
        //return parent::fetchProductsData(); // TODO: Change the autogenerated stub
    }

}